### ISSUE TITLE
This driver is not configured for integrated authentication

### ISSUE THREAD

**Issue by hwang1227** [IBMDecisionOptimization/OPL-jdbc-data-source#14]
Hi Viu-long,

I was able to access to the SQL server using below connector.

var db = JDBCConnector("jdbc:sqlserver://prd-sql;username=cfc;password=1234;databaseName=Evalue;");

Our DB team recently updated SQL server to version 2019 and I need to use window authentication to connect SQL server.

Thus I use following JDBC connector command but failed to connect to SQL server.

var db = JDBCConnector("jdbc:sqlserver://prd-sql;databaseName=Evalue;integratedSecurity=true;");

It says "This driver is not configured for integrated authentication". (Please see the [attachment)](url)

Would you please help me to solve this issue?

Thank you for your help in advance.

-Sung

![JDBC Connetion Error](https://user-images.githubusercontent.com/70233526/97050833-b181d480-1543-11eb-9556-979c3146f212.png)

**Comment by vlkong** [comment]
Hello,

The error message says it all: you are missing `jdbc_auth-8.4.0.x64.dll` in your system.

You need that dll to use `IntegratedSecurty` with the jdbc/mssql driver.

you will find this in the .zip containing the mssql-jdbc drivers (typically for 8.4.1.0, you will find the .dll under `sqljdbc_8.4.1.0_enu.zip\sqljdbc_8.4\enu\auth\x64\mssql-jdbc_auth-8.4.1.x64.dll`).

You need top copy that .dll to your PATH - From your output, either next to oplrun or next to your `java.exe`.

**Comment by hwang1227** [comment]
Thank you Viu-long for your reply.

mod and dat files are in the folder C:\Users\opl\EVOS and I copied mssql-jdbc_auth-8.4.1.x64.dll to that folder.

However I still have the same issue.

Caused by: java.lang.UnsatisfiedLinkError: no mssql-jdbc_auth-8.4.0.x64 in java.library.path: [C:\Program Files\IBM\ILOG\CPLEX_Studio129\opl\bin\x64_win64, C:\Program Files\IBM\ILOG\CPLEX_Studio129\opl\bin\x64_win64/../../bin/x64_win64, C:\Program Files\IBM\ILOG\CPLEX_Studio129\opl\bin\x64_win64/../../bin, C:\jdk-14.0.2/bin/server, C:\jdk-14.0.2/bin/server/.., C:\jdk-14.0.2/bin/server/../native_threads]

I also copied .dll file to the CLEX_Studio129 and jdk-14.0.2 folders but failed to run the model.

Would you please let me know where I should put .dll file?

Thank you for your help!
-Sung

**Comment by vlkong** [comment]
Hi,
Copying the .dll to the folder containing your .mod or .dat does not work because C:\Users\opl\EVOS is not in your system PATH.
Can you please try copying it to `C:\Program Files\IBM\ILOG\CPLEX_Studio129\opl\bin\x64_win64` ?

**Comment by hwang1227** [comment]
Viu-long,

It works now. (I copied 8.4.1.x64.dll and it didn't work so I copied 8.4.0.x64.dll)

Thank you again your help.

-Sung
