### ISSUE TITLE
Impossible to load model

### ISSUE THREAD

**Issue by wnassief** [IBMDecisionOptimization/OPL-jdbc-data-source#2]
I am still unable to make it work. I keep getting an error. Here are the details:

I am using IBM ILOG CPLEX Optimization Studio community version 12.9 and trying to run the example studio integration with the custom_data_source provided here.

Error: Impossible to load model.
Type: OPL Marker.

I basically modified/added the followings:
First, created a database in a MS SQL Server pointing to `var db = JDBCConnector("jdbc:sqlserver://AJLCD-OPCSQL03\\OPCDB01D;instanceName=SQLEXPRESS;databaseName=custom_data_source;integratedSecurity=true");` and added the data accordingly.

- edited the jdbc.js to direct the links to the correct place for my jar files 
`var jdbc_driver = "mssql-jdbc-7.4.1.jre8.jar"`
`var jdbc_driver_path = "C:/Users/username/Desktop/Models/OPL-jdbc-data-source/examples/studio_integration"`
`var libs = "C:/Users/username/Desktop/Models/OPL-jdbc-data-source/examples/studio_integration";`

Your help is appreciated. Thanks.

**Comment by vlkong** [comment]
Can you please run your model using oplrun.exe (`oplrun.exe your.mod your.dat`) and send me the full output ?

**Comment by wnassief** [comment]
Thanks for the tip. I used oplrun.exe instead of the regular default  run button and it showed me the error in details. 

The error was fixed by copying the file **sqljdbc_auth.dll** next to my java directory, right inside C:\Program Files\Java\jre_version\bin\ 

The file can be found inside the unzipped folder of Microsoft JDBC Driver 6.0 for SQL Server\sqljdbc_6.0\enu\auth\x64\sqljdbc_auth.dll

**Comment by vlkong** [comment]
Thanks for the feedback and have a nice day
