### ISSUE TITLE
JDBCConnector does not work for multiple databases

### ISSUE THREAD

**Issue by wnassief** [IBMDecisionOptimization/OPL-jdbc-data-source#3]
I managed to connect successfully to only one database using the scripts provided BUT fail to connect to multiple ones. Here is my code:

`prepare {
	includeScript("jdbc.js");
	var db = JDBCConnector("jdbc:sqlserver://AJLCD-OPCSQL03\\OPCDB01D;databaseName=custom_data_source;integratedSecurity=true");
	var db2 = JDBCConnector("jdbc:sqlserver://AJLCD-OPCSQL03\\OPCDB01D;databaseName=HOPT;integratedSecurity=true");
	db.read("Gasolines", "exec SP_CPLXI_NameGASDATA");
	db.read("Oils", "exec SP_CPLXI_NameOilData");
	db.read("GasData", "exec SP_CPLXI_GASDATA_new '" + RunLogId  + "'");
	db.read("OilData", "exec SP_CPLXI_OilData_New '" + RunLogId  + "','" + Scenario  + "'");
	db.read("OilDataBis", "exec SP_CPLXI_OilDataBis '" + RunLogId  + "','" + Scenario+ "','" + ScenarioId  + "'");
	db.update("NewResult", "exec ctcsp_CPLXO_result3 ?,?,?,?,?,?" );
}
MaxProduction = 14000;
ProdCost = 4;`

The code works fine when connecting with db string but does not work once I try to define a new db as db2 connecting to the same server but for a different instance name or database. Help is appreciated.

Here is the detailed error I get when running using oplrun.exe

> *** ERROR[SCRIPT_002] at 48:0 
jdbc.js: Scripting runtime error: (in IloOplCallJava) ilog.concert.IloException: already have a callback 
 at ilog.opl.opl_lang_wrapJNI.IloOplModel_registerPostProcessListener(Native Method) 
 at ilog.opl.IloOplModel.registerPostProcessListener(IloOplModel.java:421) 
 at com.ibm.opl.customdatasource.JdbcCustomDataSource.addDataSource(JdbcCustomDataSource.java:83) 
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
 at java.lang.reflect.Method.invoke(Unknown Source) 
 at ilog.opl.IloOplExternalCall.callStaticJava(IloOplExternalCall.java:153) 
.
*** ERROR[SCRIPT_004] at 8:0-25:0 C:\Users\user.name\Desktop\Models\OPL-jdbc-data-source\examples\studio_integration\demo.dat: Execution of "prepare" failed: "jdbc.js", line 48: IloOplCallJava: ilog.concert.IloException: already have a callback 
 at ilog.opl.opl_lang_wrapJNI.IloOplModel_registerPostProcessListener(Native Method) 
 at ilog.opl.IloOplModel.registerPostProcessListener(IloOplModel.java:421) 
 at com.ibm.opl.customdatasource.JdbcCustomDataSource.addDataSource(JdbcCustomDataSource.java:83) 
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
 at java.lang.reflect.Method.invoke(Unknown Source) 
 at ilog.opl.IloOplExternalCall.callStaticJava(IloOplExternalCall.java:153) 
.
*** ERROR[SCRIPT_005] at 8:0-25:0 C:\Users\usern.name\Desktop\Models\OPL-jdbc-data-source\examples\studio_integration\demo.dat: Script expression can not be evaluated.

**Comment by vlkong** [comment]
Hi,
It looks like Opl does not allow to register multiple listeners for post processing.
I'll work on a fix.

**Comment by NourredineHail** [comment]
Hi there, I am Wael colleague who discovered the issue; the connectivity could be to multiple SQL servers, could be 2 or more. Please take this assumption in your investigation.

Another question, is there any specific steps to follow to connect  CPLEX 12.9 or higher to an oracle database?

Morevover if I have to read data from Oracle and SQL servers would this be possible?

Thanks,

**Comment by vlkong** [comment]
Yes, nothing prevents you to connect to Oracle as well.

However you will probably need to edit jdbc.js and change the way jdbc drivers are read.
Currently, the code does:
```
// import all drivers in jdbc_driver, separated by ;. This allows to be stored at different default locations.
var drivers = jdbc_driver_path.split(";");
for (var i=0; i < drivers.length; i++) {
	IloOplImportJava(drivers[i] + "/" + jdbc_driver)
}
```
You will want to do that for SQL server drivers and Oracle drivers.
I'll also modify this.

Thanks

**Comment by NourredineHail** [comment]
We managed to edit jdbc.js to connect to an oracle database and read an OPL set (.mod) from a simple select statement. We will keep you posted if we have any issue when trying to read data from packages. Thanks a lot.

**Comment by wnassief** [comment]
Hi @vlkong any chance on getting this fixed or modifying the code to connect to multiple databases? Thanks.

**Comment by vlkong** [comment]
Hi. Branch master already had the changes for some time, but just realized that I didn't publish a release.
Please try this:
https://github.com/IBMDecisionOptimization/OPL-jdbc-data-source/releases/tag/1.3

**Comment by wnassief** [comment]
Thanks. I will try and get back to you today/tomorrow.

**Comment by wnassief** [comment]
Hello. I noticed that the jdbc file has a loop:
`for (var j=0; j < drivers.lenth; j++)`
I am not a Java programmer but could it be a typo (length vs. lenth)?

Also, would you be able to tell how the new .dat file in OPL will look like **when I add a new db connection**, given the previous one was like this:

`prepare {
	includeScript("jdbc.js");
	var db = JDBCConnector("jdbc:sqlserver:SERVER_NAME;databaseName=DATABASE_NAME;integratedSecurity=true");
  	db.read(SQL_TABLE, SQL_PROCEDURE);
    db.update(SQL_TABLE, SQL_PROCEDURE);
 }`

Thanks!

**Comment by wnassief** [comment]
It is resolved! Thanks.

The new .dat in OPL would look like this:

`includeScript("jdbc.js");`
`var db1 = JDBCConnector("jdbc:sqlserver:SERVER_NAME1;databaseName=DATABASE_NAME1;integratedSecurity=true");`
`db1.read(SQL_TABLE, SQL_PROCEDURE); 
	db1.update(SQL_TABLE, SQL_PROCEDURE);`

`var db2 = JDBCConnector("jdbc:sqlserver:SERVER_NAME2;databaseName=DATABASE_NAME2;integratedSecurity=true");`
`db2.read(SQL_TABLE, SQL_PROCEDURE);`
`db2.update(SQL_TABLE, SQL_PROCEDURE);`
