### ISSUE TITLE
Impossible to load the model

### ISSUE THREAD

**Issue by Sreyams** [IBMDecisionOptimization/OPL-jdbc-data-source#6]
I keep getting this "Impossible to load the model" error.

I see the database queries being called ok with my sqlserver database setup executing the call __JDBCConnector_read

I have added some writeln statements to show this jdbc.js

[a IloOplFile]
LOAD [a IloOplFile]
./mssql-jdbc-8.2.2.jre8.jar
[a IloOplFile]
./jdbc-custom-data-source.jar
jdbc:sqlserver://localhost;instanceName=SFICT7R3L1X2;databaseName=custom_data_source;integratedSecurity=true
[a IloOplModel]
name - Gasolines query = SELECT NAME FROM GASDATA
name - Oils query = SELECT NAME FROM OILDATA
name - GasData query = SELECT * FROM GASDATA
name - OilData query = SELECT * FROM OILDATA

Not sure how to resolve this error.

**Comment by Sreyams** [comment]
if I run this with oplrun in command window, I get this error

C:\DATA_SCIENCE\IBM CPLEX\workspace\studio_integration>oplrun demo.mod demo.dat
IBM ILOG CPLEX Optimization Studio Community Edition.  The CPLEX Optimizers will solve problems up to 1000 variables and 1000 constraints.
Problem size limit exceeded.
CP Optimizer Community Edition solves problems with search spaces up to 2^1000.
Unrestricted version options (including academia) at https://ibm.co/2s0wqSa


<<< setup

*** FATAL at 40:0 jdbc.js: Error loading a Java Runtime Environment: Can't load JVM from C:\Program Files (x86)\Java\jre1.8.0_251/bin/client/jvm.dll.
### OPL exception: Processing failed.

**Comment by vlkong** [comment]
Hi,

I think you have 2 problems:
1 - your model is too large for the community edition
2 - You are trying to use a JVM that is a 32 bits JVM (it is in `c:\Program files (x86)`) - I believe you need a 64 bits JVM, but ask for confirmation from OPL support.

Thanks

**Comment by Sreyams** [comment]
Hi,
I corrected the JVM issue. However, when I run with oplrun, I get the DB connection error as below. However, when I run a test java program that connects to the same DB using the same jdbc jar file, it works fine getting data from the GASDATA table.

Here is the screenshot from both.
![image](https://user-images.githubusercontent.com/4873175/85055135-1cbd3380-b16b-11ea-9349-d29cda7ec879.png)
![image](https://user-images.githubusercontent.com/4873175/85055232-3bbbc580-b16b-11ea-9bf6-eaa403f1243c.png)

**Comment by vlkong** [comment]
This is a well known issue with integratedsecurity.

Did you put jdbc_auth.dll in your system path ? You can copy it next to your `oplrun.exe` or in your `C:\Windows\SysWOW64`.

With sqljdbc 8.2.2, you can find the file in your 
downloaded sqljdbc_8.2.2.0_enu.zip, location: `sqljdbc_8.2\enu\auth\x64\mssql-jdbc_auth-8.2.2.x64.dll`

**Comment by Sreyams** [comment]
Thanks, that trick worked. and was able to run the model.
However, if have a duplicate value coming from the database, for example, price field, the model does not recognize duplicate value in a float .. 
Is this a known issue or is there a workaround to recognize duplicate values in example {float} xyz = ...; xyz coming from database

**Comment by vlkong** [comment]
{float} xyz = ...;  is a set of float. As with all sets, you can only have one of each.

The OPL java data source connector does not support arrays, so you will have to define your values
as a tuple with index+value, then fill an array at read time.

Something like this:

tuple floatValue {
   int index;
   float value;
}

{floatValue} xyz_with_index = ...;

then you can use opl to convert the tuplset of floatValue to array.

But there are people more knowledgeable than me on OPL, you can ask for help on https://stackoverflow.com/questions/tagged/opl

Thanks
