### ISSUE TITLE
Couldn't connect to MS SQL server

### ISSUE THREAD

**Issue by hwang1227** [IBMDecisionOptimization/OPL-jdbc-data-source#8]
HI,

I am developing a scheduling model using CPLEX Optimization Studio. To run the model, I need to read data from MS SQL server. Based on the article in this post, I downloaded jdbc driver (mssql-jdbc-8.4.0.jre14.jar) and jdbc-custom-data-source (jdbc-custom-data-source.jar) files and save files in the project folder.

I first modified JDBC.js file to update path of driver and library files.
- var jdbc_driver = "mssql-jdbc-8.4.0.jre14.jar"
- var jdbc_driver_path = "C:\\Users\\opl\\Blending" 
- var libs = "C:\\Users\\opl\\Blending";

Again I created dat file to read data from SQL server based on sql address (sql07), database name (value), username (lee), and password (1234).

prepare{
	includeScript("jdbc.js");
		
	var db = JDBCConnector("jdbc:sqlserver://sql07;user=lee;password=1234;databaseName=value;");
}

I want it to see whether I am able to access to the server, but it seems that it returns with Data parsing error (syntax error).

Would you please help me how I can access to the data set?

**Comment by vlkong** [comment]
Hi,

Can you please attach your .dat ? And if you could run your model using `oplrun` and attach the full output, it will help me diagnose your issue.

(If for some reasons you don't want to post files in this public issue, you can send them to me: viulong.kong@fr.ibm.com )

Thanks

**Comment by vlkong** [comment]
transcript from emails exchanges (for the log)

- Thanks for the .dat, I received it by email. The .dat was just a modified version of blending.dat with nearly everything commented and a `prepare` block,

- Error found: The error message you have says:
```
*** ERROR[DATA_001] at 19:7-8 blending.dat: Data parsing error: syntax error, unexpected {, expecting from or to.
*** ERROR[DATA_001] at 22:5-7 blending.dat: Data parsing error: syntax error, unexpected (identifier), expecting from or to.
*** ERROR[DATA_001] at 24:0-1 blending.dat: Data parsing error: syntax error, unexpected }, expecting $end.
```
That error message is a bit confusing but the actual error is that you need spaces after a prepare statement:

In the.dat, the prepare statement is malformed:

Actual:
```
prepare{
	includeScript("jdbc.js");	
	...
}
```

Correct one:
```
prepare {
	includeScript("jdbc.js");	
	...
}
```

**Comment by hwang1227** [comment]
After I discussed this issue with Viu-Long via e-mails, I found that I need to use mssql-jdbc-8.4.0.jre8.jar for the OPL studio (I used jre14.jar).

After changing to jre8, OPL studio is able to read data from SQL server.

Thank you Viu-Long for your help!
